### ISSUE TITLE
Request header field x-ton-client-version is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by dmitrydrynov** [ton-core/ton#1]
Hello,

I am trying to exec callGetMethod from the browser and am getting this error:
`Access to XMLHttpRequest at 'https://testnet.toncenter.com/api/v2/jsonRPC' from origin '...' has been blocked by CORS policy: Request header field x-ton-client-version is not allowed by Access-Control-Allow-Headers in preflight response.`

I'm using apiKey for TonClient() function

**Comment by kdimentionaltree** [comment]
Hello, we've allowed all headers in testnet.
Could you please check, if it works fine now?

**Comment by dvlkv** [comment]
@dmitrydrynov have you checked?

**Comment by dmitrydrynov** [comment]
No yet. I moved my get methods requests to the backend.
